-- migration 018: Fix host resource columns types to allow FLOAT values
ALTER TABLE hosts ALTER COLUMN cpu_total TYPE DOUBLE PRECISION;
ALTER TABLE hosts ALTER COLUMN cpu_used TYPE DOUBLE PRECISION;
ALTER TABLE hosts ALTER COLUMN ram_total TYPE DOUBLE PRECISION;
ALTER TABLE hosts ALTER COLUMN ram_free TYPE DOUBLE PRECISION;
ALTER TABLE hosts ALTER COLUMN disk_total TYPE DOUBLE PRECISION;
ALTER TABLE hosts ALTER COLUMN disk_free TYPE DOUBLE PRECISION;
