ALTER TABLE instances ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE volumes ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE security_groups ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE templates ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';
ALTER TABLE public_ips ADD COLUMN IF NOT EXISTS user_id VARCHAR(255) DEFAULT '';